interface exercised-interests-handler {
  use jabratech:common/types.{response,currency};
  use types.{exercised-interests-response};

  get:  func(user-email:string, currency: currency, counterparty: list<u8>, current-spot: f64, is-all: bool) -> result<exercised-interests-response, response>;
  
}